In [6]:
import requests
import pandas as pd
import json
import pprint

In [7]:
# Read the CSV file containing highest paid NBA players
salary_df = pd.read_csv('Resources/nba_salaries.csv')

In [8]:
# Isolate the names of NBA players into a list
player_names_list = salary_df["Player"].values.tolist()

In [9]:
# Run the list of names through our API call and parse out player ID's to use later

## For some reason, Kristaps and Devin Booker get dropped from the list...
## It could be a limit on the API call?

url = "https://www.balldontlie.io/api/v1/players/?search="
player_id_list = []

for name in player_names_list:
    player_url = url + f"{name}"
    player_get = requests.get(player_url)
    player_get.json()
    player_dict = json.loads(player_get.text)
    player_id_list.append(player_dict['data'][0]["id"])

IndexError: list index out of range

In [10]:
# Hint --  Give some time some the JSON to run
# Add the information to a DataFrame
player_id_df = pd.DataFrame(player_id_list)
salary_id_join = player_id_df.join(salary_df)
salary_player_id_df = salary_id_join.rename(columns={0: 'player_id'})
salary_player_id_df= salary_player_id_df[['player_id','Player','Tm','2021-22']]
salary_player_id_df

    player_id                 Player   Tm       2021-22
0         115          Stephen Curry  GSW  $45780966.00
1        1014              John Wall  HOU  $44310840.00
2         472      Russell Westbrook  LAL  $44211146.00
3         192           James Harden  BRK  $43848000.00
4         278         Damian Lillard  POR  $43750000.00
5         237           LeBron James  LAL  $41180544.00
6         140           Kevin Durant  BRK  $40918900.00
7          15  Giannis Antetokounmpo  MIL  $39344970.00
8         172            Paul George  LAC  $39344970.00
9         274          Kawhi Leonard  LAC  $39344900.00
10        443          Klay Thompson  GSW  $37980720.00
11         79           Jimmy Butler  MIA  $36016200.00
12        200          Tobias Harris  PHI  $36000000.00
13        315        Khris Middleton  MIL  $35500000.00
14        117          Anthony Davis  LAL  $35361360.00
15        176            Rudy Gobert  UTA  $35344828.00
16        228           Kyrie Irving  BRK  $34916200.00
17         37           Bradley Beal  WAS  $34502130.00